In [ ]:
#install libraries
!pip install bnlp
!pip install bnlp_toolkit
!pip install --upgrade bnlp_toolkit

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
pip install fasttext

In [ ]:
# Install necessary dependencies
!pip install bnlp3
import nltk
nltk.download('stopwords')  # Download stopwords

try:
    # Attempt to use stopwords from bnlp3 if available
    from bnlp.corpus import stopwords
    stopwords_list = stopwords()
    print("Using stopwords from bnlp3.")
except ImportError:
    # If bnlp3 does not have stopwords, use nltk as a fallback
    from nltk.corpus import stopwords
    stopwords_list = set(stopwords.words('bengali'))
    print("Using Bangla stopwords from nltk.")

# Display the list of Bangla stopwords
print(stopwords_list)


Using Bangla stopwords from nltk.
{'যাঁরা', 'হয়', 'এই', 'অর্থাত', 'হন', 'তাহলে', 'নতুন', 'এখানেই', 'প্রভৃতি', 'নেওয়া', 'ফের', 'করলে', 'তখন', 'যতটা', 'করিয়া', 'যাদের', 'একই', 'গিয়ে', 'থেকেও', 'যেন', 'সেটাও', 'মাত্র', 'সেটা', 'নয়', 'হবে', 'চালু', 'অবধি', 'টি', 'থাকবে', 'কমনে', 'স্পষ্ট', 'করছেন', 'হয়েই', 'যাওয়ার', 'সমস্ত', 'কে', 'ক্ষেত্রে', 'দিন', 'তাহার', 'নিজেই', 'সেখান', 'ছিল', 'ওঁর', 'আগামী', 'কাজে', 'নিজের', 'হোক', 'আদ্যভাগে', 'থাকা', 'অনেক', 'এল', 'কোটি', 'পরেই', 'তাই', 'করি', 'দ্বারা', 'যখন', 'থেকেই', 'গুলি', 'অবশ্য', 'পেয়ে', 'জে', 'কয়েক', 'ধামার', 'সি', 'করেছে', 'তার', 'সেই', 'ওকে', 'দেখা', 'হয়েছে', 'মোটেই', 'ইত্যাদি', 'এঁদের', 'হওয়া', 'হাজার', 'থাকায়', 'করেন', 'তবু', 'তাঁদের', 'তাও', 'চেয়ে', 'হলো', 'হয়', 'উচিত', 'জনকে', 'তারপর', 'হয়নি', 'তিনিও', 'কাছে', 'করেছিলেন', 'চায়', 'ওর', 'হলে', 'ও', 'এটা', 'সহ', 'আমাকে', 'পর্যন্ত', 'হওয়ার', 'কোনো', 'র', 'তবে', 'দিকে', 'সবার', 'দেখতে', 'ওখানে', 'প্রতি', 'এমনকী', 'গোটা', 'মাধ্যমে', 'বেশি', 'অনেকে', 'বলেন', 'জ্নজন', 'জানানো', '

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import random
import re, string
import seaborn as sns
import matplotlib.pyplot as plt

from string import punctuation
from bnlp import BasicTokenizer, NLTKTokenizer, SentencepieceTokenizer
from bnlp import BengaliWord2Vec

# Set style for plots
sns.set_style("whitegrid")
plt.style.use("ggplot")  # Changed to "ggplot" for compatibility
plt.rc("figure", autolayout=True)
plt.rc("axes", labelweight="bold", labelsize="large", titleweight="bold", titlepad=10)

# Verify available styles (optional)
print("Available styles:", plt.style.available)

# Data preprocessing
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler

# Naive Bayes
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

# PyTorch LSTM
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler

# Tokenization for LSTM
from collections import Counter
from gensim.models import Word2Vec, FastText

# Metrics and evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report


Available styles: ['Solarize_Light2', '_classic_test_patch', '_mpl-gallery', '_mpl-gallery-nogrid', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-v0_8', 'seaborn-v0_8-bright', 'seaborn-v0_8-colorblind', 'seaborn-v0_8-dark', 'seaborn-v0_8-dark-palette', 'seaborn-v0_8-darkgrid', 'seaborn-v0_8-deep', 'seaborn-v0_8-muted', 'seaborn-v0_8-notebook', 'seaborn-v0_8-paper', 'seaborn-v0_8-pastel', 'seaborn-v0_8-poster', 'seaborn-v0_8-talk', 'seaborn-v0_8-ticks', 'seaborn-v0_8-white', 'seaborn-v0_8-whitegrid', 'tableau-colorblind10']


## Define Performance Metrics & Confusion Matrix

In [ ]:
# Calculate performance metrics
def perf_matrix(y_test, y_pred):
  accuracy = accuracy_score(y_test, y_pred)
  precision = precision_score(y_test, y_pred, average='weighted')
  recall = recall_score(y_test, y_pred, average='weighted')
  f1 = f1_score(y_test, y_pred, average='weighted')

  print('Accuracy:', accuracy)
  print('Precision:', precision)
  print('Recall:', recall)
  print('F1 Score:', f1)

# Plot confusion matrix
def conf_matrix(y_test, y_pred, title, labels):
    fig, ax =plt.subplots(figsize=(4,4))
    ax=sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, cmap="Greens", fmt='g', cbar=True, annot_kws={"size":20})
    plt.title(title, fontsize=25)
    ax.xaxis.set_ticklabels(labels, fontsize=16)
    ax.yaxis.set_ticklabels(labels, fontsize=14.5)
    ax.set_ylabel('Test', fontsize=25)
    ax.set_xlabel('Predicted', fontsize=25)
    plt.show()

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
%cd drive/MyDrive/Colab Notebooks/Thesis Project/

[Errno 2] No such file or directory: 'drive/MyDrive/Colab Notebooks/Thesis Project/'
/content


In [ ]:
!ls


drive  sample_data


# Word Embedding (Fasttext)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from collections import Counter
import fasttext
import fasttext.util
from sklearn.model_selection import train_test_split

# Load the data
df = pd.read_excel('/content/drive/MyDrive/nlp project dataset/BSMDD_v3_textcleaned - 21K.xlsx')
X = df['text']

# Create a vocabulary of words from the data
corpus = [word for text in X for word in text.split()]
count_words = Counter(corpus)
sorted_words = count_words.most_common()
vocab_to_int = {w: i + 1 for i, (w, c) in enumerate(sorted_words)}

# Save the text data to a file
with open('corpus.txt', 'w') as f:
    for text in X:
        f.write(text + '\n')

# Create a FastText model
model = fasttext.train_unsupervised('corpus.txt', model='skipgram', dim=200)

# Initialize the embedding matrix
VOCAB_SIZE = len(vocab_to_int) + 1  # +1 for the padding
EMBEDDING_DIM = model.get_dimension()
embedding_matrix = np.zeros((VOCAB_SIZE, EMBEDDING_DIM))

# Update the embedding matrix with the FastText embeddings
for word, i in vocab_to_int.items():
    embedding_matrix[i] = model.get_word_vector(word)

# Print the shape of the embedding matrix
print("Embedding Matrix Shape:", embedding_matrix.shape)

# Tokenize the data using the vocabulary
text_int = []
for text in X:
    r = [vocab_to_int.get(word, 0) for word in text.split()]  # Using 0 for words not in vocab
    text_int.append(r)

# Add padding to tokens
MAX_LEN = 5000
X = pad_sequences(text_int, maxlen=MAX_LEN, padding='post')
y = df['label'].values

# Split the data into training, validation, and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.1, stratify=y_train)


Embedding Matrix Shape: (61239, 200)


# Data preprocessing for LSTM

In [ ]:
def Tokenize(column, seq_len):
    ##Create vocabulary of words from column
    corpus = [word for text in column for word in text.split()]
    count_words = Counter(corpus)
    sorted_words = count_words.most_common()
    vocab_to_int = {w:i+1 for i, (w,c) in enumerate(sorted_words)}

    ##Tokenize the columns text using the vocabulary
    text_int = []
    for text in column:
        r = [vocab_to_int[word] for word in text.split()]
        text_int.append(r)
    ##Add padding to tokens
    features = np.zeros((len(text_int), seq_len), dtype = int)
    for i, review in enumerate(text_int):
        if len(review) <= seq_len:
            zeros = list(np.zeros(seq_len - len(review)))
            new = zeros + review
        else:
            new = review[: seq_len]
        features[i, :] = np.array(new)

    return sorted_words, features

In [ ]:
max_len = 5000

In [ ]:
vocabulary, tokenized_column = Tokenize(df["text"], max_len)

In [ ]:
vocabulary[:20]

[('সাথে', 29468),
 ('চাই', 19782),
 ('করেছি', 16442),
 ('কথা', 13859),
 ('জানি', 13230),
 ('করছি', 12983),
 ('সত্যিই', 11552),
 ('সম্পর্কে', 9940),
 ('খারাপ', 9904),
 ('নিজেকে', 9832),
 ('সময়', 9731),
 ('ভাল', 9522),
 ('অনুভব', 8436),
 ('শেষ', 8184),
 ('ছিলাম', 8007),
 ('সাহায্য', 7345),
 ('জীবন', 7093),
 ('বন্ধু', 7092),
 ('বোধ', 7029),
 ('পছন্দ', 5722)]

In [ ]:
tokenized_column[3:6]

array([[    0,     0,     0, ...,   241, 22712,   821],
       [    0,     0,     0, ...,   240,   741,    33],
       [    0,     0,     0, ...,   306,   488,    88]])

In [ ]:
df["text"].iloc[10]

'সত্যিই বুক পেতে চাই বন্ধু পরিবারের সাথে প্রতিক্রিয়া দেখাতে চাই অবস্থা কারো খারাপ মধ্যবিত্ত এসেছি বাবামা আছেন সত্যিই যত্ন নেন বন্ধু আছেন যত্নশীল মিডল স্কুলে হাইস্কুলের জালফের পরিশ্রম ছাড়াই দুর্দান্ত গ্রেড পেয়েছি এমনকি ভাল বন্ধুও কারণে হাই স্কুলে জুনিয়র বছরের অন্যরকম অনুভব সময়ে একমাত্র উপায় জানতাম কিভাবে ব্যাখ্যা কেবল অনুভব করছিলাম ক্লাসের শেষ মিনিটে সাধারণত করেছিলাম শেষ পরিবর্তে নিজেকে হোমওয়ার্ক করছি বন্ধুদের বাবামা এমনকি জিএফ সাথেই নিজেকে ড্রেসিং সামাজিক মিথস্ক্রিয়া পেয়েছি একবারে পরিবর্তে সময়ের সাথে সাথে ক্রমাগত বেড়েছে কারণে ভিন্নভাবে অভিনয় অনুসন্ধানে চারপাশকে দোষ করেছি ছিলামআমি সম্পর্কে জানি সাধারণভাবে সুন্দর বুদ্ধিমান ব্যক্তি বলার অপেক্ষা রাখে কারো ভালো স্মার্ট স্কুলে বেড়ে ওঠা সবসময়ই কারণেই নিজেকে সত্যিকারের ব্রিলিয়ান্ট লোকের বেষ্টিত পেয়েছি যেগুলোর সাথে ক্রমাগত নিজেকে তুলনা জিনিসটি প্রথমে আসলে আত্মবিশ্বাসকে বাড়িয়ে গ্রেডের সবচেয়ে বুদ্ধিমান বাচ্চাটিকে দেখব ভাল বন্ধু পরীক্ষায় তাকাবে ভাববে বাহ লীগে আছি অবশ্যই স্মার্ট মাঝে মাঝে অ্যাসাইনমেন্ট পুরোপুরি ব্যর্থ এটিকে ভাল 

In [ ]:
tokenized_column[10]

array([  0,   0,   0, ...,  80, 424,  56])

## Train - Validation - Test split

In [ ]:
df.head(10)

text  label
0  মানসিক শারীরিকভাবে অসুস্থ ক্লান্ত পুরো জীবন শা...      1
1  দয়া সাথে থাকুন অত্যন্ত দীর্ঘ আপনাকে পড়তে উত্...      1
2  জানতাম সাথে ভুল লোক খারাপ জীবন কাটিয়েছে সম্পূ...      1
3  অনেটিভ ইংরেজি স্পিকারের অনুসরণ বিরক্তিকর অপ্রত...      1
4  অনেটিভ ইংরেজি স্পিকারের অনুসরণ বিরক্তিকর অপ্রত...      1
5  প্রথমে আপনাকে প্রশ্ন উপস্থাপন যাচ্ছি পারবেন দি...      1
6  রেফারেন্সের বয়সী পুরুষ থাকার সাইক ওয়ার্ড বের...      1
7  দৈর্ঘ্যের ক্ষমাপ্রার্থী বোঝানোর বের আলিঙ্গন বল...      1
8  উপকারী সাব দয়া আপলোড পোস্ট সেরা জায়গা মোবাইল...      1
9  দীর্ঘ পোস্ট জীবনের সারসংক্ষেপ টাইম লাইনটি একটু...      1

In [ ]:
X = tokenized_column
y = df['label'].values
y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.1, stratify=y_train)

In [ ]:
(unique, counts) = np.unique(y_train, return_counts=True)
np.asarray((unique, counts)).T

array([[   0, 7883],
       [   1, 7892]])

# PyTorch datasets and dataloaders

In [ ]:
BATCH_SIZE = 8
EPOCHS = 5 #Number of training epoch
LR = 0.003 #Learning rate
DROPOUT = 0.5 #LSTM Dropout
WEIGHT_DECAY = 0.003
LSTM_LAYERS = 2 #Number of stacked LSTM layers
HIDDEN_DIM = 100 #number of neurons of the internal state (internal neural network in the LSTM)

NUM_CLASSES = 2 #We are dealing with a multiclass classification of 2 classes
BIDIRECTIONAL = True #Boolean value to choose if to use a bidirectional LSTM or not

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
train_data = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
test_data = TensorDataset(torch.from_numpy(X_test), torch.from_numpy(y_test))
valid_data = TensorDataset(torch.from_numpy(X_valid), torch.from_numpy(y_valid))

In [ ]:
train_loader = DataLoader(train_data, shuffle=True, batch_size=BATCH_SIZE, drop_last=True)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=BATCH_SIZE, drop_last=True)
test_loader = DataLoader(test_data, shuffle=True, batch_size=BATCH_SIZE, drop_last=True)

## PyTorch BiLSTM modeling

In [ ]:
class BiLSTM_Sentiment_Classifier(nn.Module):

    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_classes, lstm_layers, bidirectional,batch_size, dropout):
        super(BiLSTM_Sentiment_Classifier,self).__init__()

        self.lstm_layers = lstm_layers
        self.num_directions = 2 if bidirectional else 1
        self.hidden_dim = hidden_dim
        self.num_classes = num_classes
        self.batch_size = batch_size


        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        self.lstm = nn.LSTM(embedding_dim,
                            hidden_dim,
                            num_layers=lstm_layers,
                            dropout=dropout,
                            bidirectional=bidirectional,
                            batch_first=True)

        self.fc = nn.Linear(hidden_dim*self.num_directions, num_classes)
        self.softmax = nn.LogSoftmax(dim=1)

    def forward(self, x, hidden):
        self.batch_size = x.size(0)
        ##EMBEDDING LAYER
        embedded = self.embedding(x)
        #LSTM LAYERS
        out, hidden = self.lstm(embedded, hidden)
        #Extract only the hidden state from the last LSTM cell
        out = out[:,-1,:]
        #FULLY CONNECTED LAYERS
        out = self.fc(out)
        out = self.softmax(out)

        return out, hidden

    def init_hidden(self, batch_size):
        #Initialization of the LSTM hidden and cell states
        h0 = torch.zeros((self.lstm_layers*self.num_directions, batch_size, self.hidden_dim)).detach().to(DEVICE)
        c0 = torch.zeros((self.lstm_layers*self.num_directions, batch_size, self.hidden_dim)).detach().to(DEVICE)
        hidden = (h0, c0)
        return hidden

In [ ]:
model = BiLSTM_Sentiment_Classifier(VOCAB_SIZE, EMBEDDING_DIM, HIDDEN_DIM,NUM_CLASSES, LSTM_LAYERS,BIDIRECTIONAL, BATCH_SIZE, DROPOUT)
model = model.to(DEVICE)

#Initialize embedding with the previously defined embedding matrix
model.embedding.weight.data.copy_(torch.from_numpy(embedding_matrix))
#Allow the embedding matrix to be fined tuned to better adapt to out dataset and get higher accuracy
model.embedding.weight.requires_grad=True

print(model)

BiLSTM_Sentiment_Classifier(
  (embedding): Embedding(61239, 200)
  (lstm): LSTM(200, 100, num_layers=2, batch_first=True, dropout=0.5, bidirectional=True)
  (fc): Linear(in_features=200, out_features=2, bias=True)
  (softmax): LogSoftmax(dim=1)
)


In [ ]:
criterion = nn.NLLLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay = WEIGHT_DECAY)

### BiLSTM Training loop

In [ ]:
total_step = len(train_loader)
total_step_val = len(valid_loader)

early_stopping_patience = 4
early_stopping_counter = 0

valid_acc_max = 0 # Initialize best accuracy top 0

for e in range(EPOCHS):

    #lists to host the train and validation losses of every batch for each epoch
    train_loss, valid_loss  = [], []
    #lists to host the train and validation accuracy of every batch for each epoch
    train_acc, valid_acc  = [], []

    #lists to host the train and validation predictions of every batch for each epoch
    y_train_list, y_val_list = [], []

    #initalize number of total and correctly classified texts during training and validation
    correct, correct_val = 0, 0
    total, total_val = 0, 0
    running_loss, running_loss_val = 0, 0


    ####TRAINING LOOP####

    model.train()

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(DEVICE), labels.to(DEVICE) #load features and targets in device

        h = model.init_hidden(labels.size(0))

        model.zero_grad() #reset gradients

        output, h = model(inputs,h) #get output and hidden states from LSTM network

        loss = criterion(output, labels)
        loss.backward()

        running_loss += loss.item()

        optimizer.step()

        y_pred_train = torch.argmax(output, dim=1) #get tensor of predicted values on the training set
        y_train_list.extend(y_pred_train.squeeze().tolist()) #transform tensor to list and the values to the list

        correct += torch.sum(y_pred_train==labels).item() #count correctly classified texts per batch
        total += labels.size(0) #count total texts per batch

    train_loss.append(running_loss / total_step)
    train_acc.append(100 * correct / total)

    ####VALIDATION LOOP####

    with torch.no_grad():

        model.eval()

        for inputs, labels in valid_loader:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)

            val_h = model.init_hidden(labels.size(0))

            output, val_h = model(inputs, val_h)

            val_loss = criterion(output, labels)
            running_loss_val += val_loss.item()

            y_pred_val = torch.argmax(output, dim=1)
            y_val_list.extend(y_pred_val.squeeze().tolist())

            correct_val += torch.sum(y_pred_val==labels).item()
            total_val += labels.size(0)

        valid_loss.append(running_loss_val / total_step_val)
        valid_acc.append(100 * correct_val / total_val)

    #Save model if validation accuracy increases
    if np.mean(valid_acc) >= valid_acc_max:
        torch.save(model.state_dict(), './state_dict.pt')
        print(f'Epoch {e+1}:Validation accuracy increased ({valid_acc_max:.6f} --> {np.mean(valid_acc):.6f}).  Saving model ...')
        valid_acc_max = np.mean(valid_acc)
        early_stopping_counter=0 #reset counter if validation accuracy increases
    else:
        print(f'Epoch {e+1}:Validation accuracy did not increase')
        early_stopping_counter+=1 #increase counter if validation accuracy does not increase

    if early_stopping_counter > early_stopping_patience:
        print('Early stopped at epoch :', e+1)
        break

    print(f'\tTrain_loss : {np.mean(train_loss):.4f} Val_loss : {np.mean(valid_loss):.4f}')
    print(f'\tTrain_acc : {np.mean(train_acc):.3f}% Val_acc : {np.mean(valid_acc):.3f}%')

In [ ]:
# Loading the best model
model.load_state_dict(torch.load('./state_dict.pt'))

### BiLSTM Testing

In [ ]:
model.eval()
y_pred_list = []
y_test_list = []
for inputs, labels in test_loader:
    inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
    test_h = model.init_hidden(labels.size(0))

    output, val_h = model(inputs, test_h)
    y_pred_test = torch.argmax(output, dim=1)
    y_pred_list.extend(y_pred_test.squeeze().tolist())
    y_test_list.extend(labels.squeeze().tolist())

In [ ]:
label = ['0','1']

In [ ]:
print('Classification Report for Bi-LSTM :\n', classification_report(y_test_list, y_pred_list, target_names=label))

In [ ]:
perf_matrix(y_test_list, y_pred_list)
#conf_matrix(y_test_list,y_pred_list,'PyTorch Bi-LSTM Sentiment Analysis\nConfusion Matrix', label)